PREFIX schema:  <https://schema.org/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT
{
    ?this schema:text [ a xsd:string ] ;
        schema:spokenByCharacter [ a rdfs:Resource ] ;
        schema:isBasedOn [ a rdfs:Resource ] .
}
WHERE {}
